// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzB4o0mgGns8hzYt_OVQlsz5SqzCZN21k',
    appId: '1:642677562167:web:ba5a9945fd661303bcd8b2',
    messagingSenderId: '642677562167',
    projectId: 'priyafashion-1a790',
    authDomain: 'priyafashion-1a790.firebaseapp.com',
    storageBucket: 'priyafashion-1a790.firebasestorage.app',
    measurementId: 'G-YPNMJ17P6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBd5VKTiDuySvIczPSam5sg6SZF9JhaVQ',
    appId: '1:642677562167:android:790d5692e38da210bcd8b2',
    messagingSenderId: '642677562167',
    projectId: 'priyafashion-1a790',
    storageBucket: 'priyafashion-1a790.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBd5VKTiDuySvIczPSam5sg6SZF9JhaVQ',
    appId: '1:642677562167:ios:790d5692e38da210bcd8b2',
    messagingSenderId: '642677562167',
    projectId: 'priyafashion-1a790',
    storageBucket: 'priyafashion-1a790.firebasestorage.app',
    iosBundleId: 'com.handloombazar.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBd5VKTiDuySvIczPSam5sg6SZF9JhaVQ',
    appId: '1:642677562167:ios:790d5692e38da210bcd8b2',
    messagingSenderId: '642677562167',
    projectId: 'priyafashion-1a790',
    storageBucket: 'priyafashion-1a790.firebasestorage.app',
    iosBundleId: 'com.handloombazar.shop',
  );
}
